Ammended version untested

diff --git a/.github/workflows/assignment4.yml b/.github/workflows/assignment4.yml
--- a/.github/workflows/assignment4.yml
+++ b/.github/workflows/assignment4.yml
@@ -101,11 +101,11 @@ jobs:
           docker load -i pet-order.tar
 
       - name: Start Docker containers
+        if: always()
         run: |
-          docker compose up -d
-          echo "Container pet-store #1 up and running" >> log.txt
-          echo "Container pet-store #2 up and running" >> log.txt
-          echo "Container pet-order up and running" >> log.txt
+          docker ps --format "{{.Names}}" | grep -qx "pet-store1" && echo "Container pet-store #1 up and running" >> log.txt || echo "Container pet-store #1 failed to run" >> log.txt
+          docker ps --format "{{.Names}}" | grep -qx "pet-store2" && echo "Container pet-store #2 up and running" >> log.txt || echo "Container pet-store #2 failed to run" >> log.txt
+          docker ps --format "{{.Names}}" | grep -qx "pet-order"  && echo "Container pet-order up and running"   >> log.txt || echo "Container pet-order failed to run"   >> log.txt
 
       - name: Install pytest
         run: pip install pytest requests
